# Generated by Django 3.1.4 on 2021-01-03 09:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=30)),
                ('property_type', models.CharField(max_length=10)),
                ('offer_type', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=15)),
                ('zip_code', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=15)),
                ('bedrooms', models.SmallIntegerField()),
                ('bathrooms', models.SmallIntegerField()),
                ('property_size', models.SmallIntegerField()),
                ('year', models.IntegerField(default=2020)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=15)),
                ('details', models.TextField()),
                ('contact', models.IntegerField(null=True)),
                ('status', models.CharField(default='Available', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='display.property')),
                ('Attic', models.BooleanField(default=False)),
                ('Garden', models.BooleanField(default=False)),
                ('Microwave', models.BooleanField(default=False)),
                ('Dishwasher', models.BooleanField(default=False)),
                ('Gym', models.BooleanField(default=False)),
                ('Patio', models.BooleanField(default=False)),
                ('Fireplace', models.BooleanField(default=False)),
                ('High_ceilings', models.BooleanField(default=False)),
                ('Swimming_Pool', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Properties',
                'verbose_name_plural': 'Properties',
            },
            bases=('display.property',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=10)),
                ('type', models.CharField(default=django.contrib.auth.models.User, max_length=6)),
                ('wishlist', models.CharField(max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='imgtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('message', models.TextField(max_length=500)),
                ('status', models.CharField(default='Open', max_length=10)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.feature')),
            ],
        ),
    ]
