# Generated by Django 3.1.5 on 2021-01-06 08:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Seen', 'Seen'), ('Close', 'Close')], default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Broker', 'Broker'), ('User', 'User')], default=django.contrib.auth.models.User, max_length=6),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale')], max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Office', 'Office'), ('Land', 'Land')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Block', 'Block')], default='Available', max_length=10),
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='broker/')),
                ('quotes', models.CharField(max_length=30)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
