# Generated by Django 3.1.5 on 2021-01-06 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('display', '0002_auto_20210106_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='broker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
