# Generated by Django 3.1.5 on 2021-01-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20210106_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriber', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
