# Generated by Django 3.1.5 on 2021-01-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Appartment', 'Appartment'), ('House', 'House'), ('Office', 'Office'), ('Land', 'Land')], max_length=10),
        ),
    ]
