# Generated by Django 3.1.5 on 2021-01-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20210115_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
